apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: demo-app
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: demo-app
    minReplicas: 1
    maxReplicas: 10
    metrics:
        - type: Resource
          resource:
              name: cpu
              targetAverageUtilization: 50
        - type: Resource
          resource:
              name: memory
              targetAverageUtilization: 60
